### ISSUE TITLE
VL Coverage Analysis: LTS Countries

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/Engagements#34]
VL Request
--
Request from: Viral Load Community of Practice (COOP) and/or Short Term Task Team (ST3)
Requested from George to the ICPI Liaison to the ST3/COOP, Yaa

**Deadline Friday 9/28** @hessionra and @kkale25 please let me know if you are unable to complete by tomorrow. Shouldn't take too long!

**Output**: Slide deck visualizing: 
- FY17 VL coverage for 23 LTS OUs
- FY18 VL coverage targets for 23 LTS OUs
- FY18Q3 VL testing volume or VL coverage to date*

**Tasks:**
- [x] Create GitHub ticket (Yaa)
- [x] Create a folder in ICPI engagements (Yaa)
- [x] Go to POART folders [here ](https://www.pepfar.net/OGAC-HQ/OGAC/poart/SharedDocuments)and save all FY18Q3 POART slides available in that folder (Jasmine) )
- [x] If slides don’t exist, reach out to CL (Jasmine)
- [x] Review slides and compile results (Rebecca, Kashmira, Jasmine)
- [x] Send info to Yaa (Rebecca, Kashmira, Jasmine)
- [x] Send info to George (Yaa) [(final slides on SP)](https://www.pepfar.net/OGAC-HQ/icpi/Shared Documents/ICPI Engagement/VL FY18Q3 POART Slides/Final VL Slides)
- [x] Ask George to provide an update on how the analysis was used (Yaa)
- [x] Follow up (Yaa)

Review of Q3 POART slides for all OUs to extract VL data
Slides in pepfar.net [Engagement folder - VL](https://www.pepfar.net/OGAC-HQ/icpi/Shared Documents/ICPI Engagement/VL FY18Q3 POART Slides) & assignment & status 

Please Check Below once Complete. Most files are in the sharepoint folder. JB has requested the additional files. Please add any comments below. 

**Kashmira**
- [x] Completed All OUs on the list below?
- [x] Ethiopia
- [ ] Burundi (asked CL for slides)
- [x] Uganda
- [x] Cameroon
- [x] Cote d'Ivoire
- [x] Kenya
- [x] Nigeria
- [x] Rwanda
- [x] DRC

**Rebecca**
- [x] Completed All OUs on the list below?
- [X] South Sudan
- [X] Tanzania
- [x] Haiti
- [x] Botswana
- [x] Lesotho
- [ ] Malawi
- [x] Mozambique
- [x] Namibia
- [x] South Africa

**Jasmine**
- [x] Completed All OUs on the list below?
- [x] Eswatini (Swaziland) - no VL slide - referenced VL as part of TLD Transition
- [x] Zambia 2 slides
- [x] Zimbabwe- No VL slides
- [x] Ukraine - 1slides
- [x] Vietnam

Final Slides Saved on SP
--
[VL Summary OGAC Request Slides on SP](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FVL%20FY18Q3%20POART%20Slides%2FFinal%20VL%20Slides&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by jb3436** [comment]
Using the ICPI Master Contact List [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCommunications%2FMaster%20ICPI%20Contact%20List&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) I sent an email to the CLs and SI advisors and cc'd ICPI and @Yabayabadoo 

Subject: Request: FY18Q3 POART Slides?

**Comment by jb3436** [comment]
@Yabayabadoo did you send the info to George?

**Comment by jb3436** [comment]
Final slides sent to George. [VL Summary OGAC Request saved here on SP in Engagements Folder ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FVL%20FY18Q3%20POART%20Slides%2FFinal%20VL%20Slides&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by jb3436** [comment]
**Next Steps:** 

- [ ] @Yabayabadoo to follow up with George on how the slides were used and what decisions came from them.

**Comment by jb3436** [comment]
Email sent to ICPI Community 10/5
Subject: Available: Compiled FY18Q3 POART Slides on SP 

Summary of Email sent to ICPI
--
Dear ICPI Community, 
 
Through an ST3 and Community of Practice (COOP) request, ICPI was asked to complete an analysis based on the data presented in the FY18Q3 POART slides. 
 
In order to complete the analysis, we first had to compile all of the FY18Q3 POART slides. 
 
If your team is doing a similar activity or if you all would like to review the FY18Q3 POART slides to see the different ways the country teams used and presented data, they are saved here on SP. There are only two OU’s missing. If you happen to have those slides, please share them and I can upload them to SharePoint. 
 
The below OUs slides are in the folder unless otherwise noted. :
•         Ethiopia 
•         Uganda
•         Cameroon
•         Cote d'Ivoire
•         Kenya
•         Nigeria
•         Rwanda
•         DRC
•         South Sudan
•         Tanzania
•         Haiti
•         Botswana
•         Lesotho
•         Malawi
•         Mozambique
•         Namibia
•         South Africa
•         Eswatini (Swaziland)  
•         Zambia 
•         Zimbabwe
•         Ukraine 
•         Vietnam
•         Burundi (do not have slides

**Comment by jb3436** [comment]
SharePoint Links
--

- Final slides sent to George. [VL Summary OGAC Request saved here on SP in Engagements Folder ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FVL%20FY18Q3%20POART%20Slides%2FFinal%20VL%20Slides&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
- Final Excel Tool [on SP Here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FVL%20FY18Q3%20POART%20Slides%2FFinal%20VL%20Slides&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
