### ISSUE TITLE
Internal Checklist for Reverse TDYs

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#9]
Pre rTDY 
o	Interagency buy-in received from country and from HQ
-	Has the requestor discussed TDY with interagency space in country?
-	Have objectives been agreed upon?
-	Have outputs/outcomes been agreed upon?
-	Who is the M&E POC from each agency?
o	Engagement form completed
o	Pre-visit discussion with country team completed
-	Clarify objectives, outputs, skills, projects, timeline, etc.
o	Email sent via ICPI to all stakeholders informing of request
o	Rough agenda set for visit
o	Meetings with necessary stakeholders set up
o	Conference room needs set up
o	Logistical information sent to rTDYers prior to arrival 
-	Visitors Guide
-	Meeting invites
-	“Virtual” Training materials (if relevant)

During rTDY
o	Regular check-in with rTDYers conducted as appropriate
-	Are objectives of rTDY being met?
-	Are critical stakeholders missing? 
-	Are meetings required with SI/M&E/CL/Chair/ECT POCs? 
-	Are there any potential issues to be aware of?
o	Communication with country team occurs as needed
-	Has anything changed since arrival in country?
-	Are there any potential issues to be aware of?
o	Continued liaising/connecting with appropriate resources at ICPI
o	Email sent via ICPI with updated information on rTDY

Post rTDY
o	Workplan/primary activities to be continued after visit developed and shared by rTDYers
o	rTDY experience shared through debrief presentation at ICPI inbrief
o	Email sent via ICPI with updated information and official “close” of request if appropriate
o	Outputs and deliverables from rTDY shared appropriately within country and at HQ
o	Regular communication, if needed, to maintain momentum on activities from rTDY
o	Send survey for feedback (at end of rTDY) and 1 month later
o	TOT report submitted no later than 6 months later

**Comment by kkale25** [comment]
Checklist for Reverse TDYs
FOR INTERNAL ICPI USE

Pre rTDY 
o	Get interagency buy-in from country and from HQ
-	Has the requestor discussed TDY with interagency space in country?
-	Have objectives been agreed upon? Have outputs/outcomes been agreed upon?
-	Who are the SI TWG co-chairs in country? Have they been looped in?
-	Request writing confirmation of interagency support in country
o	Ensure engagement form is completed
o	Have a pre-visit call with country team and other relevant stakeholders
-	Clarify objectives, outputs, skills, projects, timeline, etc.
o	Send email via ICPI to all stakeholders informing them of request
o	Develop rough agenda for visit with country input
o	Set up necessary meetings with stakeholders 
o	Send logistical information to rTDYers prior to arrival 
-	Visitors Guide
-	Meeting invites
-	“Virtual” Training materials (if relevant)

During rTDY
o	Regularly check-in with rTDYers as appropriate
-	Are objectives of rTDY being met?
-	Are critical stakeholders missing? 
-	Are additional meetings required with SI/M&E/CL/Chair/ECT POCs? 
-	Are there any potential issues to be aware of?
o	Maintain communication with country team as needed
-	Has anything changed since arrival in country?
-	Are there any potential issues to be aware of?
o	Continue liaising/connecting with appropriate resources at ICPI
o	Send next email via ICPI with updated information on rTDY

Post rTDY
o	rTDYers to develop and share workplan outlining primary to be continued after visit
o	rTDYers to share visit experience through debrief presentation at ICPI inbrief
o	Send final email via ICPI with updated information and official “close” of request if appropriate
o	Share outputs and deliverables from rTDY within country and at HQ
o	Continue regular communication, if needed, to maintain momentum on activities from rTDY
o	Send survey for experience feedback (at end of rTDY) and 1 month later for follow-up
o	Ensure TOT report submitted no later than 6 months after visit

**Comment by jb3436** [comment]
Let's share with leads on 7/16

**Comment by jb3436** [comment]
Will convert into a task list in a github issue for new rTDYs - similar to onboarding checklist

**Comment by jb3436** [comment]
Checklist for TDY to ICPI
--
**TDY-ER Name**  ______________
**ICPI POC Name** ______________

**Pre rTDY**
**Get interagency buy - in from country and from HQ**
   - [ ]  Has the requestor discussed TDY with interagency space in country?
   - [ ]  Have objectives been agreed upon? Have outputs/outcomes been agreed upon?
   - [ ]  Who are the SI TWG co - [ ] chairs in country? Have they been looped in?
   - [ ]  Request writing confirmation of interagency support in country
 - [ ]  Ensure engagement form is completed
 - [ ]  Have a pre visit call with country team and other relevant stakeholders
   - [ ]  Clarify objectives, outputs, skills, projects, timeline, etc.
 - [ ]  Send email via ICPI to all stakeholders informing them of request
 - [ ]  Create GitHub Ticket
 - [ ]  Develop rough agenda for visit with country input
 - [ ]  Set up necessary meetings with stakeholders
 - [ ]  Send logistical information to rTDYers prior to arrival
   - [ ]  Visitors Guide
   - [ ]  Meeting invites
   - [ ]  &quot;Virtual&quot; Training materials (if relevant)

**During rTDY**

 - [ ]  Regularly check - in with rTDYers as appropriate
   - [ ]  Are objectives of rTDY being met?
   - [ ]   Are critical stakeholders missing?
   - [ ]  Are additional meetings required with SI/M&amp;E/CL/Chair/ECT POCs?
   - [ ]  Are there any potential issues to be aware of?
 - [ ]  Maintain communication with country team as needed
   - [ ]  Has anything changed since arrival in country?
   - [ ]  Are there any potential issues to be aware of?
 - [ ]  Continue liaising/connecting with appropriate resources at ICPI
 - [ ]  Send next email via ICPI with updated information on rTDY

**Post rTDY**

 - [ ]  rTDYers to develop and share workplan outlining primary to be continued after visit
 - [ ]  rTDYers to share visit experience through debrief presentation at ICPI inbrief
 - [ ]  Send final email via ICPI with updated information and official &quot;close&quot; of request if appropriate
 - [ ]  Share outputs and deliverables from rTDY within country and at HQ
 - [ ]  Continue regular communication, if needed, to maintain momentum on activities from rTDY
 - [ ]  Send survey for experience feedback (at end of rTDY) and 1 month later for follow - up
 - [ ]  Ensure TOT report submitted no later than 6 months after visit

**Knowledge management and Comms**

 - [ ]  Send email from ICPI to stakeholders
 - [ ]  Create GitHub issue in Engagements
 - [ ]  Create SharePoint folder in Engagements Log Folder
