### ISSUE TITLE
June 2021 Onboarding Checklist

### ISSUE THREAD

**Issue by gsoybel** [ICPI/Engagements#94]
- [x] Update registration form | **4/16** | @hhanfi 
- [x] Set up meeting with TechChange | **Week of 4/26** | @kkale25 
- [x] Finalize agenda |**Week of 4/26** | @kkale25 
- [x] Double check that content for MER 2.5 is updated / **Week of 4/26**/ @kkale25 
- [x] Send out registration email | **5/10**  Registration will end on 5/14 | @HoustonJamie  @kkale25 
- [x] Create Sharepoint folder for training 5/12 @gsoybel 
- [x] Create registrations List in Excel| **5/17** | @gsoybel 
- [x] Send Specific Session Save the Dates | **Week of 5/17** | @hhanfi 
- [x] Confirm office hours on June 8th works with all POCs | **Week of 5/17** | @kkale25 
- [x] Finalize Attendee List |  **5/21** | @HoustonJamie and Leads
- [x] Kick-off Meeting to POCs and facilitators | **Meeting week of 5/24** | @HoustonJamie 
- [x] Enroll Attendees in PVA | **5/24** | @hhanfi 
- [x] Send Attendees Welcome Email | **no later than 5/25** | @HoustonJamie @kkale25 
- [ ] Send Save-the-Date to Attendees | **5/25** | @HoustonJamie 
- [ ] -Send office hours invite to Attendees and Facilitators | **invite sent by 5/25 for June 8 from 8-10AM EST** | @HoustonJamie 
- [x] Update Day 1-2 Feedback Survey | **Week of 5/24** | @gsoybel @hhanfi 
- [x] Update Day 3-5 Feedback Survey | **Week of 5/24** | @gsoybel @hhanfi 

- [ ] Finalize Run of Show documents |June 4| Facilitators
- [ ] Feedback Survey PowerPoint | post-training | @gsoybel @jordanadeleon @ikabore 
- [ ] Send final email with resources and thanks to participants - Tuesday after training - @jordanadeleon

**Comment by gsoybel** [comment]
Hey all - just created the checklist for the upcoming onboarding. Kashmira - please feel free to edit dates where needed. 

Many thanks,
Geoff
