### ISSUE TITLE
October Onboarding Checklist

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#96]
- [x] 9/1: Update registration form  @kunnicak 
- [x] 9/3 Finalize agenda @kkale25 
- [x] Week of 9/6 Set up meeting with TechChange  @kkale25 
- [x] Week of 9/6 Double check with instructors that content is updated @kkale25 
- [x] 9/13 Send out registration email; Registration will end on 9/17 | @HoustonJamie  @kkale25 
- [x] Week of 9/6 Create Sharepoint folder for training 5/12 @kunnicak  
- [x] 9/20 Create registrations List in Excel @kunnicak @gsoybel 
- [x]  Week of 9/6 Send Specific Session Save the Dates @kunnicak 
- [x]  Week of 9/13 Confirm office hours date/time and check with all POCs  @kkale25 
- [x] 9/27 Finalize Attendee List @HoustonJamie and Leads
- [x] 9/30 at 2PM EST Kick-off Meeting to POCs and facilitators  @kkale25 
- [x] 10/14 Finalize Run of Show documents
- [x] 10/1 Enroll Attendees in PVA @hhanfi 
- [x] 10/1 Send Attendees Welcome Email @HoustonJamie @kkale25 
- [x] Week of 10/4 Send Save-the-Date to Attendees @kunnicak 
- [x] Week of 10/4 Send office hours invite to Attendees and Facilitators @kunnicak 
- [x]  Week of 10/14 Update Day 1-2 Feedback Survey @gsoybel @hhanfi 
- [x] Week of 10/14 Update Day 3-5 Feedback Survey  @gsoybel @hhanfi 
- [x] TBD Feedback Survey PowerPoint 
- [ ] TBD Send final email with resources and thanks to participants - @kunnicak @HoustonJamie

**Comment by kunnicak** [comment]
![image](https://user-images.githubusercontent.com/85315227/132899707-3475ab30-c500-4e4c-86b7-cbee164529c3.png)
