### ISSUE TITLE
ICPI Onboarding June 2022 Checklist

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#98]
- [x] - Registration form closes 5/11 
- [x] - Compile registration information and Leads review by 5/13 @kunnicak @HoustonJamie 
- [x] - Leads finalize names (if needed) on 5/16 @HoustonJamie 
- [x] - Finalize [agenda ](https://pepfar.sharepoint.com/:b:/r/sites/ICPI/Shared%20Documents/Trainings/ICPI%20Onboarding%20Training%20(June%202022)/Facilitator%20Materials/ICPI%20Onboarding%20Training_June%202022_Agenda.pdf?csf=1&web=1&e=95QukN)by 5/13 @kkale25 
- [x] - Finalize confirmation email by 5/13 @kunnicak 
- [x] - Hide HSS session from PVA by 5/17 @kunnicak @myang511 
- [x] - F/u with HSS group for updated session content @HoustonJamie @KateWilkinsMPH 
- [x] - Confirmation email to participants goes out on @5/17  @kunnicak to send
- [x] - Enroll attendees in PVA 5/17 @kunnicak @myang511 
- [x] - Send out training save the dates to participants no later than 5/20 @kunnicak
- [x] - Send out invite for Kick-off meeting with ICPI staff for Wednesday 5/18 at 12PM EST @kunnicak 
- [x] - Draft materials for Welcome Meeting + Kick off meeting @kkale25 
- [x] - Send out Welcome Meeting invite to participants, ICPI Leads, and TC for Thursday 5/19 at 12PM EST @kunnicak 
- [x] - Send out Tech Office Hours invite (proposing 1.5 hours) for Tuesday 5/31 at 8AM EST @kunnicak 
- [x] - Send out session-specific save the dates for ICPI Staff no later than 5/20 @kunnicak 
- [x] - Create sharepoint folder for training no later than 5/13 @kunnicak 
- [x] - Get Run of Show links from TechChange before 5/18
- [x] - Run of Shows due 5/26 by POCs
- [ ] - TechChange to create link PDFs week of 5/30
- [x] - Do sharepoint link checks beforehand to make sure they all work week of 5/30 @HoustonJamie @kunnicak 
- [x] - Update training surveys week of 5/30 @kkale25
