### ISSUE TITLE
Oct 2022 Onboarding Training Checklist

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#99]
- [x] Registration form closes 10/26
- [x]  Compile registration information and Leads review by 10/27 @kkale25 
- [x] Send out confirmation email to participants by 10/27 @kunnicak @kkale25 
- [x] Finalize agenda by 10/6 @kkale25 
- [x] Enroll participants into PVA COB 10/7 @kunnicak 
- [x] Send email with PVA instructions, agenda, and office hours instructions by 10/10 @kkale25 
- [x] Send out training save the dates to participants and staff no later than 10/10 @kunnicak
- [x] Send out invite for Welcome meeting by 10/10 to participants, ICPI Leads, and TC for Wednesday 10/13 at 8AM EST @kunnicak 
- [x] Send out session-specific save the dates for ICPI Staff no later than 10/14 @kunnicak 
- [x] Finalize materials for Welcome Meeting by 10/17 @kkale25 
- [x] Send out Tech Office Hours invite to participants and support staff for Tuesday 10/18 at 8AM EST @kunnicak 
- [x] Create sharepoint folder for training no later than 10/14 @kunnicak 
- [x] Get Run of Show links from TechChange @kkale25 
- [x] Run of Shows due to TC by 10/17 
- [ ] Do sharepoint link checks beforehand to make sure they all work by 10/18  @HoustonJamie @kunnicak 
- [ ] Update training surveys by 10/17 @kkale25
